android: [AArch64] Use GlobalISel MatchTable Combiner Backend
Porting of commit 655714a "[AArch64] Use GlobalISel MatchTable Combiner Backend"

Fixes the following building errors:

FAILED: out/soong/.intermediates/external/llvm-project/llvm/lib/Target/AArch64/llvm-gen-aarch64/gen/AArch64GenO0PreLegalizeGICombiner.inc
...
warning: '-gen-global-isel-combiner' is deprecated and will be removed soon; please use '-gen-global-isel-combiner-matchtable' instead
note: See https://discourse.llvm.org/t/rfc-matchtable-based-globalisel-combiners
error: Could not find AArch64O0PreLegalizerCombinerHelper