android: AMDGPU/GlobalISel: Introduce post-legalize combiner
android: AMDGPU/GlobalISel: Introduce post-legalize combiner

Port to Android.bp of commit
fee41517fe0 ("AMDGPU/GlobalISel: Introduce post-legalize combiner")

Fixes the following build error:

external/llvm-project/llvm/lib/Target/AMDGPU/AMDGPUPostLegalizerCombiner.cpp:229:10:
fatal error: 'AMDGPUGenPostLegalizeGICombiner.inc' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>