android: AMDGPU/GlobalISel: Add pre-legalize combiner pass
Port to Android.bp of commit
a174f0da62f ("AMDGPU/GlobalISel: Add pre-legalize combiner pass")

Fixes the following build error:

external/llvm-project/llvm/lib/Target/AMDGPU/AMDGPUPreLegalizerCombiner.cpp:32:10:
fatal error: 'AMDGPUGenPreLegalizeGICombiner.inc' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>