android: [AMDGPU] Use GlobalISel MatchTable Combiner Backend
Porting of commit 8444038 "[AMDGPU] Use GlobalISel MatchTable Combiner Backend"

Fixes the following building errors:

FAILED: out/soong/.intermediates/external/llvm-project/llvm/lib/Target/AMDGPU/llvm-gen-amdgpu/genAMDGPUGenPreLegalizeGICombiner.inc
...
warning: '-gen-global-isel-combiner' is deprecated and will be removed soon; please use '-gen-global-isel-combiner-matchtable' instead
note: See https://discourse.llvm.org/t/rfc-matchtable-based-globalisel-combiners
error: Could not find AMDGPUPreLegalizerCombinerHelper