android: add "-Wno-unused-variable" cflag
Required to avoid the following building error with Android 11

external/llvm-project/llvm/lib/Transforms/Instrumentation/MemorySanitizer.cpp:4705:12:
error: unused variable 'Success' [-Werror,-Wunused-variable]
      bool Success = maybeHandleSimpleNomemIntrinsic(I, /*trailingFlags=*/1);
           ^
1 error generated.