android: [Analysis] Move TargetLibraryInfo data to TableGen
Porting of commit c9f5734 "[Analysis] Move TargetLibraryInfo data to TableGen"

Fixes the following building error:

In file included from external/llvm-project/llvm/lib/Analysis/ConstantFolding.cpp:28:
external/llvm-project/llvm/include/llvm/Analysis/TargetLibraryInfo.h:75:10: fatal error: 'llvm/Analysis/TargetLibraryInfo.inc' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.