android: add support for libLLVMTableGenGlobalISel (v2)
Fixes the following building error:

external/llvm/utils/TableGen/GlobalISel/CodeExpander.h:50:
error: undefined reference to 'llvm::CodeExpander::emit(llvm::raw_ostream&) const'

(v2) Changes due to commit fa3d789 "[RFC][TableGen] Restructure TableGen Source"