Fix building with mainline AOSP
In AOSP version 14 some build warnings became errors, e.g.:

-----------------------------------------------------------------------
error: external/llvm-project/llvm/lib/ExecutionEngine/MCJIT/Android.bp:1:1: module "libLLVM17MCJIT" variant "linux_glibc_x86_64_static": clang: property is deprecated, see Changes.md file
error: external/llvm-project/llvm/lib/ExecutionEngine/MCJIT/Android.bp:1:1: module "libLLVM17MCJIT" variant "linux_glibc_x86_64_static": clang_cflags: property is deprecated, see Changes.md file
-----------------------------------------------------------------------

Remove the deprecated options as suggested in build/make/Changes.md

The compilation flags previously under clang_cflags are now moved to
cflags.

Note that for the build to succeed something like the following needs to
be added to the BoardConfig.mk file:

-----------------------------------------------------------------------
BUILD_BROKEN_PLUGIN_VALIDATION := soong-llvm17
-----------------------------------------------------------------------

This avoids the following error:

-----------------------------------------------------------------------
internal error: New plugins are not supported; however ["soong-llvm17"] were found. Please reach out to the build team or use BUILD_BROKEN_PLUGIN_VALIDATION (see Changes.md for more info).
fatal errors encountered
-----------------------------------------------------------------------