android: [AMDGPU] Eliminate InstCombineTables.td. NFC.
Porting of commit 979462c "[AMDGPU] Eliminate InstCombineTables.td. NFC."

Fixes the following building error:

error: external/llvm-project/llvm/lib/Target/AMDGPU/Android.bp:63:1: module "llvm22-gen-instcombine": module source path "external/llvm-project/llvm/lib/Target/
AMDGPU/InstCombineTables.td" does not exist