android: [JITLink][COFF] Implement include/alternatename linker directive.
Porting of commit 8818137 ("[JITLink][COFF] Implement include/alternatename linker directive.")

Fixes the following building errors:

In file included from external/llvm-project/llvm/lib/ExecutionEngine/JITLink/COFFDirectiveParser.cpp:13:
external/llvm-project/llvm/lib/ExecutionEngine/JITLink/COFFDirectiveParser.h:30:10: fatal error: 'COFFOptions.inc' file not fou
nd
         ^~~~~~~~~~~~~~~~~
1 error generated.

In file included from external/llvm-project/llvm/lib/ExecutionEngine/JITLink/COFF_x86_64.cpp:14:
In file included from external/llvm-project/llvm/lib/ExecutionEngine/JITLink/COFFLinkGraphBuilder.h:21:
external/llvm-project/llvm/lib/ExecutionEngine/JITLink/COFFDirectiveParser.h:30:10: fatal error: 'COFFOptions.inc' file not fou
nd
         ^~~~~~~~~~~~~~~~~
1 error generated.

In file included from external/llvm-project/llvm/lib/ExecutionEngine/JITLink/COFFLinkGraphBuilder.cpp:12:
In file included from external/llvm-project/llvm/lib/ExecutionEngine/JITLink/COFFLinkGraphBuilder.h:21:
external/llvm-project/llvm/lib/ExecutionEngine/JITLink/COFFDirectiveParser.h:30:10: fatal error: 'COFFOptions.inc' file not fou
nd
         ^~~~~~~~~~~~~~~~~
1 error generated.